# Generated by Django 4.2.1 on 2023-07-21 00:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='original')),
                ('name_image', models.CharField(max_length=150, null=True)),
                ('name_segmentada', models.CharField(max_length=150, null=True)),
                ('name_recortada', models.CharField(max_length=150, null=True)),
                ('color_dominante', models.CharField(max_length=150, null=True)),
                ('paleta_colores', models.CharField(max_length=150, null=True)),
                ('saburra', models.CharField(max_length=150, null=True)),
                ('textura', models.CharField(max_length=150, null=True)),
                ('porcentaje', models.CharField(default='0.0 %', max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
