# Generated by Django 4.2.1 on 2023-06-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='segmentada',
            field=models.CharField(default='lengua1.jpg', max_length=100),
            preserve_default=False,
        ),
    ]
